frontend/app/index.jsx

Removes the forwarding code as it is not complatable with Azure.
The software no longer attempts to forward the browser to pluto-start.
Yes. This is completely safe. The code was put in in one block, save it originally was set to timeout after one thousand milliseconds not three thousand. Removing it should do nothing apart from cause the software to stop forwarding to a currently broken URL.

Remove Forwarding to pluto-start

---

frontend/app/PremiereVersionChange/PremiereVersionChange.tsx

Chrome is preventing the automatic load of projects due to pop-up blocking.
This change will open the project and close the window if no popup blocker is detected. If a popup blocker is detected then a message "Ready to go! Please click *here* to open project"

Clarify project opening for user

---

frontend/app/ProjectEntryList/ProjectDeleteDataComponent.tsx

Hides the bucket options when the S3 switch is off.
Off.
On.
This was tested on a machine running macOS 12.6.8 under minikube 1.31.2.

Hide Bucket Options when S3 Switch Is Off

---

frontend/app/multistep/ProjectCreateMultistepNew.tsx
frontend/app/multistep/projectcreate_new/NameComponent.tsx
frontend/app/styles/app.css

This change removes unnecessary content for non-admin users when creating a new project.
The project name placeholder has also been changed to encourage users to use a descriptive project name.
Non-admin users will now see this at step 2 of creating a project:

Do not allow users to change filename unless admin

---

frontend/app/Selectors/TemplateSelector.jsx
frontend/app/multistep/postrun/MetadataComponent.jsx
frontend/app/multistep/projecttemplate/TypeSelectorComponent.jsx
frontend/app/multistep/projecttype/ProjectTypeComponent.jsx
frontend/package.json
frontend/yarn.lock

This makes text visible in form boxes in dark mode on various administration pages.
It also fixes a link on one of the pages and makes various boxes wider so larger strings can be displayed in them.
The text is visible under dark mode. The link works. Many boxes can now display longer strings. 

Fix For Display of Text in Dark Mode

---

frontend/app/ObituariesList/ObituariesList.tsx
frontend/app/ProjectEntryList/AssetFolderLink.tsx
frontend/app/ProjectEntryList/ProjectEntryEditComponent.tsx
frontend/app/ProjectEntryList/ProjectsTable.tsx
frontend/app/misc/utils.ts
frontend/app/multistep/projectcreate_new/ProjectCreatedComponent.tsx
frontend/package.json
frontend/yarn.lock

This change allows users to navigate to the Edit Project page on a row click. Previously this was done by clicking a pencil icon.  Rows and the Asset Folder button now lighten on the row for clarity.

Edit project on row click

---

frontend/app/index.jsx

Forwards to pluto-start if the user is not logged in after three seconds.
User that are not logged in get forwarded to pluto-start after three seconds.
Tested on the dev. system.

Forward to pluto-start if the User is not Logged in

---

frontend/app/ProjectEntryList/ApplicableRulesSelector.tsx
frontend/app/ProjectEntryList/ProjectEntryEditComponent.tsx

This change prevents users from setting both Deep Archive and Deletable as they are mutually exclusive. An "Are you sure?" dialogue box appears when changing the setting from Deep Archive to Deletable. 
Tested on local minikube and the dev system

Use radio buttons for media management options

---

app/services/BackupLauncher.scala
app/services/NewProjectBackup.scala

Adds a new job that deletes audio backup files and their database entries. 
The correct data is deleted.
This only works on the FileEntry table so the new audio backups that are referenced in the AssetFolderFileEntry table will be safe.

Deletion of Pointless Audio Backups

---

frontend/app/CommissionsList/CommissionEntryDeliverablesComponent.tsx

Makes the whole row for a deliverable on the commission page into a link and removes the open button.
The new links work.

Deliverables Row Link

---

frontend/app/multistep/commissioncreate_new/CommissionTitleComponent.tsx
frontend/app/multistep/projectcreate_new/ConfigurationComponent.tsx

Stops the use of underscores in commission and project titles. If the user enters an underscore a warning will be displayed.
Underscores can now not be used in commission and project titles.

Stop Use of Underscores in Commission and Project Titles

---

frontend/app/CommissionsList/CommissionEntryEditComponent.tsx

This change fixes a bug where the SAVE CHANGES button was not rendering when a new completion date was set.
Tested locally and on the dev system

Render SAVE button on completion date change

---

app/controllers/DeleteJobController.scala
app/models/DeleteJob.scala
conf/routes
frontend/app/DeletionRecords/DeletionRecord.tsx
frontend/app/DeletionRecords/DeletionRecords.tsx
frontend/app/DeletionRecords/helpers.ts
frontend/app/index.jsx
frontend/types/types.d.ts

Adds persistent deletion records.
Deletion records can be accessed by administrators even if the project record has been deleted.

Persistent Deletion Records

---

Makefile
README.md
frontend/app/CommissionsList/CommissionEntryEditComponent.tsx

- After editing a commission and clicking the SAVE CHANGES button, the user is notified if the save was successful. 
- The user is not redirected away from the edit commission page when saving changes.
- `Makefile` added for quicker local development

Commission edit

---

frontend/app/ProjectEntryList/ProjectEntryEditComponent.tsx

Removes the storage section from project pages.
The broken storage section no longer displays.

Removing Storage Section

---

app/models/ProjectEntryFilterTerms.scala

This change allows a `PUT` request to `api/project/list` to filter by `status` with a body of ```{
"match": "W_EXACT",
"status": "Completed"
}```
Tested on minikube and the dev system

Add project status filter term

---

app/controllers/MissingFilesController.scala
conf/routes
frontend/app/ProjectEntryList/ProjectEntryEditComponent.tsx

Adds display of data on files found in the project that are not in the asset folder.
The recorded missing file data is displayed in the interface.

Display Data on Missing Files

---

frontend/app/ProjectEntryList/ProjectEntryEditComponent.tsx

Stops users setting the status of projects with one or more missing files to Completed.
Users should not be able to set files to Completed if they have at least on missing file.

Ban Setting the Project Status to Completed if There Are Missing Files

---

frontend/app/ProjectEntryList/ProjectsTable.tsx

Adds a custom right click menu to project lists.
The menu works.

Custom Right Click Menu for Project Lists

---

frontend/app/CommissionsList/CommissionsList.tsx

Adds a custom right click menu to commission lists.
The menu works.

Custom Right Click Menu for Commission Lists

---

app/controllers/ProjectEntryController.scala
conf/routes
frontend/app/ProjectEntryList/ProjectEntryEditComponent.tsx
frontend/app/ProjectEntryList/helpers.ts
frontend/package.json
frontend/yarn.lock

Adds a download button for the project file.
User should be able to download project files from project pages.

Download Button for Project Files

---

app/controllers/ProjectEntryController.scala
conf/routes
frontend/app/CommissionsList/CommissionDeleteDataComponent.tsx
frontend/app/CommissionsList/CommissionEntryEditComponent.tsx
frontend/app/CommissionsList/helpers.ts
frontend/app/ProjectEntryList/ProjectEntryList.tsx
frontend/app/ProjectEntryList/ProjectsTable.tsx
frontend/app/ProjectEntryList/helpers.ts

Moves project list sorting from the client to the server.
Project lists are now sorted on the server side.

Server Side Sorting For Project Lists

---

frontend/app/multistep/commissioncreate_new/CommissionTitleComponent.tsx
frontend/app/multistep/projectcreate_new/ConfigurationComponent.tsx
frontend/app/multistep/projectcreate_new/ObituaryComponent.tsx
frontend/app/multistep/projectcreate_new/ProductionOfficeComponent.tsx
frontend/app/multistep/projectcreate_new/TemplateComponent.tsx

Makes some text larger.
Some text is larger.

Making Some Text Larger

---

frontend/app/CommissionsList/CommissionsList.tsx

Removes some code which may be causing commisson lists not to display correctly for some users.
No users have issues with the commission lists.
This was tested on a machine running macOS 12.6.8 under minikube 1.31.2.

Removes Possibly Broken Code

---

frontend/app/CommissionsList/CommissionsList.tsx

Makes the userAllowed method able to cope if confidential is undefined and if user is null.
Less errors displaying the commission lists should be seen.
This was tested on a machine running macOS 12.6.8 under minikube 1.31.2.

Make userAllowed Method More Robust

---

frontend/package.json
frontend/yarn.lock

Forces installation of Ellipitc version 6.5.7 as recommened by Snyk.
The correct version of Ellipitic is installed and pluto-core still works.

Force Installation of Elliptic Version 6.5.7

---

frontend/app/CommissionsList/CommissionEntryEditComponent.tsx
frontend/app/CommissionsList/CommissionsList.tsx
frontend/app/ProjectEntryList/ProjectEntryEditComponent.tsx
frontend/app/ProjectEntryList/ProjectsTable.tsx

Checks the user name as lower case.
Upper case user names should no longer cause permission issues.

Check User Name as Lower Case

---

frontend/app/multistep/commissioncreate_new/CommissionTitleComponent.tsx

Adds some text.
The text displays.
This was tested on a machine running macOS 12.6.8 under minikube 1.31.2.

Add Place Holder Text on New Commission Page

---

frontend/app/multistep/commissioncreate_new/CommissionTitleComponent.tsx

Removes some styling from a menu.
The menu displays data in a way that allows access to all the items.

Removing Styling

---

app/models/ProjectEntry.scala
app/services/CommissionStatusPropagator.scala

These changes should result in more consistent and reliable updates, ensuring that all eligible projects are correctly updated to "Completed" when their parent commission is set to "Completed."
- Added transaction verification to ensure project status updates are committed correctly
- Improved logging to track update progress and failures
- Clarified project status change logic in `getProjectsEligibleForStatusChange`
- Fixed issue where projects were incorrectly reporting success despite status mismatch
- Removed duplicate RabbitMQ messages
The changes ensure that when a commission status changes, all eligible projects are properly updated and verified within a single transaction.
Tested on the dev system.

Fix project update logic

---

frontend/app/common/UsersAutoComplete.tsx

Stops an error message displaying when the user selects an owner from the menu after typing part of the name.
The error message does not display when the user selects an owner from the menu after typing part of the name.

Only Validate Owners when Enter Pressed

---

frontend/app/ProjectEntryList/ProjectEntryEditComponent.tsx

Adds a warning and abort button if the project is to be set to Completed and is less than twenty four hours old.
The warning and button display when the project is to be set to completed and the project is less than twenty four hours old.

Warn if the Project is to be Set to Completed and is Less Than Twenty Four Hours Old

---

frontend/app/CommissionsList/CommissionEntryEditComponent.tsx

Adds a warning and abort button if the commission is to be set to Completed and is less than twenty four hours old.
The warning and button display when the commission is to be set to completed and the commission is less than twenty four hours old.

Warn if the Commisson is to be Set to Completed and is Less Than Twenty Four Hours Old

---

app/controllers/ProjectEntryController.scala
app/models/AssetFolderFileEntryDAO.scala

Deletes asset folder based project backups.
Asset folder based project backups are deleted.
Tested on the dev. system.

Delete Asset Folder Based Project Backups

---

app/auth/BearerTokenAuth.scala
conf/application.conf

Times out keys after a certain amount of seconds and attempts to download new keys before they are used.
Requires new setting of auth.keyTimeOut in a number of seconds be present in the application configuration file.
Keys should be invalid less often.

Time Out and Refresh Keys

---

app/controllers/Files.scala
app/models/ProjectEntry.scala
app/services/PremiereVersionConverter.scala
frontend/app/PremiereVersionChange/PremiereVersionChange.tsx

Allows users to attempt to update large project files. When an update fails, instructions are displayed.
Also fixes an issue with the mostRecentBackup function. This can now have the storage to check on fed into it so it can output correct data.
Users can now attempt to update large project files.

Allow Users to Attempt to Update Large Project Files

---

frontend/app/ProjectEntryList/ProjectEntryEditComponent.tsx

Allows the Premiere Pro version  to be set when it not already populated.
The Premiere Pro version can be set even when it is not populated.

Set the Premiere Pro version When it is not Populated

---

.github/workflows/build.yml
app/services/ProjectBackupAssetFolder.scala

Adds an optional pause to the backup loop which is set in the configuration file. It takes the value of backup.pauseMilliseconds, which should be a number in milliseconds.
The backup loop can now be set to pause between items.

Optional Pause in Backup Loop

---

app/controllers/ProjectEntryController.scala
conf/routes
frontend/app/ProjectEntryList/BackupEntry.tsx
frontend/app/ProjectEntryList/ProjectBackups.tsx

Allows administrators to attempt to restore backed up project files.
Project files can be restored.

Restore Project Files

---

app/controllers/ProjectEntryController.scala
build.sbt

Causes an e-mail to be sent if a sensitive project is created. Requires data similar to the following be added to the pluto-core configuration file to work as intended: -
play.mailer {
host = "smtp.a.org"
port = 25
ssl = no
tls = no
tlsRequired = no
user = null
password = null
debug = no
timeout = null
connectiontimeout = null
mock = no
props {
}
}
mail {
subject = "String"
sender_name = "String"
sender_address = "a@a.org"
recipient_name = "String"
recipient_address = "b@b.org"
}
The e-mail is sent.

Send an E-mail if a Sensitive Project is Created

---

app/controllers/ProjectEntryController.scala
frontend/app/ProjectEntryList/BackupEntry.tsx
frontend/app/ProjectEntryList/ProjectBackups.tsx

Allows users to restore back ups of Premiere Pro and After Effect projects files.
Users can restore the files.

Allow Users to Restore Premiere Pro and After Effects Project Files

---

app/controllers/ProjectEntryController.scala
conf/routes
frontend/app/ProjectEntryList/AssetFolderProjectBackups.tsx

Allows users to restore Cubase and Audition project files. If the 'Restore' button is pressed a folder called 'RestoredProjectFiles' should get created in the project's asset folder containing all of the backup project files.
The folder gets created successfully.

Restore Cubase and Audition Project Files
